package io.github.maxwellnie.free.jdbc.statement;


import java.io.Serializable;

/**
 * @author Maxwell Nie
 */
public interface Configuration extends Serializable {
    long serialVersionUID = 135238493948L;

    /**
     * @return <code>Statement.RETURN_GENERATED_KEYS</code> or <code>Statement.NO_GENERATED_KEYS</code>
     */
    int getAutoGeneratedKeys();

    int getFetchSize();

    int getQueryTimeout();

    int getResultSetConcurrency();

    int getResultSetType();

    int getHoldability();
}
