package io.github.maxwellnie.free.jdbc.statement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * @author Maxwell Nie
 */
public class PreparedIntegratedStatement extends BaseIntegratedStatement<PreparedStatement, PreparedIntegratedStatement> {
    public PreparedIntegratedStatement(Connection connection) {
        super(connection);
        super.integratedStatement = this;
    }

    @Override
    public PreparedIntegratedStatement createStatement(String sql) throws StatementException {
        this.sql = sql;
        validateConnection();
        validateSql();
        try {
            if (configuration != null)
                statement = StatementUtils.prepareStatement(connection, sql, configuration.getAutoGeneratedKeys(), configuration.getResultSetType(), configuration.getResultSetConcurrency(), configuration.getHoldability());
            else
                statement = StatementUtils.prepareStatement(connection, sql);
            applyConfiguration();
        } catch (SQLException e) {
            throw new StatementException("Prepared statement creation failed for SQL: " + sql + ", Error: " + e.getMessage() +
                    ", Expected: successful prepared statement creation, Actual: SQLException during creation", e);
        }
        return integratedStatement;
    }

    protected boolean defaultExecute() throws SqlExecutionException {
        try {
            return statement.execute();
        } catch (SQLException e) {
            throw new SqlExecutionException("Prepared statement execution failed for SQL: " + sql + ", Error: " + e.getMessage() +
                    ", Expected: successful execution, Actual: SQLException during execution", e);
        }
    }

}