package io.github.maxwellnie.free.jdbc.statement;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * @author Maxwell Nie
 */
public class SimpleIntegratedStatement extends BaseIntegratedStatement<Statement, SimpleIntegratedStatement> {
    public SimpleIntegratedStatement(Connection connection) {
        super(connection);
        this.integratedStatement = this;
    }

    @Override
    public SimpleIntegratedStatement createStatement(String sql) throws StatementException {
        this.sql = sql;
        validateConnection();
        validateSql();
        try {
            if (configuration != null)
                statement = StatementUtils.statement(connection, configuration.getResultSetType(),
                        configuration.getResultSetConcurrency(), configuration.getHoldability());
            else
                statement = StatementUtils.statement(connection);
            applyConfiguration();
        } catch (SQLException e) {
            throw new StatementException("Simple statement creation failed for SQL: " + sql + ", Error: " + e.getMessage() +
                    ", Expected: successful statement creation, Actual: SQLException during creation", e);
        }
        return integratedStatement;
    }

    @Override
    public <P> SimpleIntegratedStatement parameterize(ParametersHandler<Statement, P> parametersHandler, P parameters) throws StatementException {
        throw new StatementException("Simple statement does not support parameterization. Use prepared or callable statement instead." +
                ", Expected: parameterized statement capability, Actual: simple statement which doesn't support parameters");
    }

    @Override
    protected boolean defaultExecute() throws SqlExecutionException {
        try {
            if (configuration != null && configuration.getAutoGeneratedKeys() > 0) {
                return statement.execute(sql, configuration.getAutoGeneratedKeys());
            } else
                return statement.execute(sql);
        } catch (SQLException e) {
            throw new SqlExecutionException("Simple statement execution failed for SQL: " + sql + ", Error: " + e.getMessage() +
                    ", Expected: successful execution, Actual: SQLException during execution", e);
        }
    }
}